### ISSUE TITLE
Give Binoculars a zoom option

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#104]
https://www.civilgamers.com/community/threads/binocular-zoom.5383/

**Comment by Freezgam03** [comment]
@Copeless When are you able to do this? Obviously not needed to be done urgently at all, just wanted to know.

**Comment by gnoment** [comment]
@McYeke think this can be transferred from mrp?

**Comment by auburncivilnetworks** [comment]
This exists on the server. Marking this as complete
