### ISSUE TITLE
Removing HL2 Voicelines

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#109]
https://www.civilgamers.com/community/threads/remove-hl2rp-voicelines.5687/

**Comment by gnoment** [comment]
@McYeke pretty sure this is in chatsounds for darkrp, ftp

**Comment by GarrySwepman** [comment]
I personally like having the HL2 voice lines in game especially "run for your lives" but I wouldn't mind losing the mingey albeit iconic voice lines like "sometimes I dream about cheese" for example.

**Comment by ghost** [comment]
Resolved with:
https://github.com/civilnetworks/darkrpmodification/pull/12
