### ISSUE TITLE
Search in Vcomputers by username/SteamID

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#110]
https://www.civilgamers.com/community/threads/vcomputers-search-by-username-steamid.4310/

**Comment by McYeke** [comment]
Further added suggestion: https://www.civilgamers.com/community/threads/fix-the-scriptnet-search-feature.7687/ 

To ensure the search function works appropriately.

**Comment by McYeke** [comment]
Closed to #731
