### ISSUE TITLE
Being able to lock doors when hacked

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#113]
Essentially, when hacking a door, you have the option to lock the door for 10-15 seconds.

Recent suggestion:
https://www.civilgamers.com/community/threads/lock-doors-by-hacking-them.5754/

**Comment by Kw1ll** [comment]
should be alot longer than 10-15 seconds considering time it takes to hack, maybe 1 minute at most

**Comment by gnoment** [comment]
same as #361
