### ISSUE TITLE
Reduce respawn timer for foundation on surface

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#12]
https://www.civilgamers.com/community/threads/increasing-surface-warfare-by-reducing-surface-spawn-time.4023/#post-27243

MTFs rarely roam surface because it takes a lot of time to get back to surface after being killed by CI which makes the gameplay stale on surface, this would help an important thing that needs to be added is a rule saying that backspawning during raids it not allowed, this is already enforced but it is not clear in the rules. Another way this could be fixed is the spawn timer increasing if you die in / near your spawn. If this was implemented for all spawns and not just garage it would give CI a chance during floor 3 raids, since it's currently very hard to do anything on floor 3 due to A1 and O1 spawning over and over right in middle of floor 3

**Comment by CoolfraeCN** [comment]
Would be better do detect if any CI/Civillians are in the vicinity of the spawn (inside the foundation base at surface) and then disallow spawns. Else allow normal spawn times. - Content team backlog meeting

**Comment by Kw1ll** [comment]
Returning to FTP - If we want spawns to do as coolfrae suggests we can just make a seperate ticket, would be preferable to get the reduced spawner out sooner

**Comment by gnoment** [comment]
done on live
