### ISSUE TITLE
Orsis 4x scope is off-center

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#124]
![Image](https://user-images.githubusercontent.com/65787083/183437403-a36d03bc-19de-4a86-ac8f-22e816d03398.png)

**Comment by Copeless** [comment]
Should be uploaded to live from restarts, when confirmed working on live mark complete and close issue

**Comment by McYeke** [comment]
@Copeless - Still off centre same with 2x

**Comment by RequisJaquavian** [comment]
2x Scope aligned
