### ISSUE TITLE
SCPs further acting clarification for RP

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#127]
https://www.civilgamers.com/community/threads/scps-further-clarification-in-rp.4209/

**Comment by Kw1ll** [comment]
@McYeke if you could start work on this or get someone to do so it would be nice

**Comment by McYeke** [comment]
In progress - 75% complete, awaiting review and assistance to flesh this out appropriatly.

**Comment by gnoment** [comment]
already completed

**Comment by Rushi123456** [comment]
Re-opening - Not completed yet

**Comment by metropolitan24** [comment]
@Rushi123456 @gnoment @McYeke 
Can we get some clarity on what this is?

**Comment by McYeke** [comment]
Closed: No longer required and due to SCP changes will make this significantly harder to implement, supers have cited lack of time to complete.
