### ISSUE TITLE
Improve the !banjob command

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#167]
https://www.civilgamers.com/community/threads/improve-the-banjob-command.5780/

**Comment by KaptianCore** [comment]
could do an overhaul like coolfrae's credit system adding configuration for what jobs there are. making everything configurable. maybe even ability to add new ban commands.

**Comment by gnoment** [comment]
no description, thread deleted

**Comment by gnoment** [comment]
closed the wrong thread. calls for steamid job bans.

**Comment by ghost** [comment]
Moved to Revision Required, specification needed.

**Comment by auburncivilnetworks** [comment]
Closing due to lack of info and dead link
