### ISSUE TITLE
Allow Site Advisors to call a Code Black

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#170]
https://www.civilgamers.com/community/threads/allow-sa-to-call-code-black-evacuation-not-nuke.6257/

Just the code, not the nuke itself.

**Comment by Rushi123456** [comment]
Make code black be able to called by any CL4+, but would be a IC policy for only Site Advisors+ to be able to call it.

**Comment by KaptianCore** [comment]
Inherently done when made so CL4's can call code blacks.
