### ISSUE TITLE
Decrease CoM printing credit replenishment times

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#177]
https://www.civilgamers.com/community/threads/decrease-com-printing-credit-replenishment-times.6107/

**Comment by McYeke** [comment]
Resolved - quicker credit replenishment time / infinite credits

**Comment by McYeke** [comment]
Re-Opened - This seems to no longer happen.

**Comment by RequisJaquavian** [comment]
Fixed - Now has a 1 minute cooldown
