### ISSUE TITLE
Remove /advert

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks-projects/SCP_Public_Development#246]
https://www.civilgamers.com/community/threads/changing-the-advert-substring.8477/#post-53934

We have /oc, /advert causes issues as DarkRP players have it binded and end up spamming it quite a bit, no need to have two versions of the same command.

**Comment by Kw1ll** [comment]
Ontop of this, Content Team has agreed to remove /oc from Cl1/Cl2 personnel as to prevent misuse - this extends to surface jobs and having mayor be the only capable person of using /oc for now

**Comment by KaptianCore** [comment]
Was completed a few weeks ago.
