### ISSUE TITLE
Change the voice line button to H, add player customization for it

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks-projects/SCP_Public_Development#248]
https://www.civilgamers.com/community/threads/suggestions-for-912-breaches-and-others.8651/#post-53964

When SCPs breach, such as 9000, their voice lines or other abilities are on "G" which is the same button used to break doors, this should be changed to H so that breaking doors is exclusively used for G.

Ontop of this, making it so that the player can optimize which button they wish and bind should be a thing (make it a customizable option)

**Comment by McYeke** [comment]
SCP-457 is currently bound to G - Looking to change to KEY_H
SCP-912 is bound to G - Looking to change to KEY_H
SCP-9000-A-3 is bound to G - Looking to change to KEY_H
SCP-9000-A-3 echo time looking to extend from 1s to a increased value pending testing
SCP-939s scream is bound to G  - Looking to change to KEY_H

**Comment by McYeke** [comment]
Completed, however customisation will NOT be added, keys changed to KEY_H instead of KEY_G
