### ISSUE TITLE
Add 'Held Weapons' log category

### ISSUE THREAD

**Issue by cloakical** [civilnetworks-projects/SCP_Public_Development#253]
Feature specification:
- Will require modifying klogs to add a new log category (I don't mind giving hlogs out to developers without FTP access, so this is a no-access required ticket)
- Should be called 'Held Weapons' and logs the weapons held by a player in the last 30 seconds
- You'll need to either use hooks or a timer to keep track of what weapons people have been holding within the last 30 seconds at all times, so you can log when needed. Need to clear out data that is older than 30 seconds else it'll be too much to store.
- Format for log item should be as follows: `{Player}'s held weapon history: vguns_acr (holding), keys (2sec ago), vclipboard (15sec ago)` - in this example this would be someone who held a clipboard 15 seconds ago, then changed to keys, and then changed to an ACR 2 seconds ago.
- We should log a held weapons event into hlogs every time they get a kill, or are killed themselves. This means each PvP death should produce 2 logs (an event for the killer and the victim), a player dying to non-PvP sources should produce 1 log (just the victim).

**Comment by KaptianCore** [comment]
Unfortunately this isn't a no access ticket due to kadmin now being the logging system
