### ISSUE TITLE
Ranger-Law enforcement Officer rebranding

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks-projects/SCP_Public_Development#258]
Change name from "Ranger" to "Law Enforcement Officer"
Add a "Sherriff" Job (identical kit to Ranger for now)
Add a police vehicle https://steamcommunity.com/sharedfiles/filedetails/?id=1086831691&searchtext=1989+chevrolet (this is the only workable one I found, would need slight remodeling and idk what else)
Add Jailor NPC and Jail zones for surface PD building

**Comment by Kw1ll** [comment]
Ontop of this, we need to find a Police Car model on the workshop for addition, this should look decent with a good wireframe as to make sure it produces the least amount of lag possible whilst still being fit for the server. Me and @McYeke will mostly look at vehicle models as it is something we have been doing for a while, as such this will stay FTP+

**Comment by Kw1ll** [comment]
Ticket updated for different plans

**Comment by 0-Marco** [comment]
Was this ran through with the content team @Kw1ll ?

**Comment by Kw1ll** [comment]
yes @0-Marco
