### ISSUE TITLE
Intercom Expansion 

### ISSUE THREAD

**Issue by MistJules** [civilnetworks-projects/SCP_Public_Development#266]
Suggestion: https://www.civilgamers.com/community/threads/intercom-expansion-suggestion.9711/

This will add more lines and places for the intercom system to announce or make callouts for the players.

Adds more lines to the intercom system for frequently used messages and announcements.

"D-class Mass Termination Authorized"
"Heavy Containment Zone / Personnel Wing/Opening in 30 Seconds / Now"
"Tesla Gate Systems Engaged / Disengaged"
"Sitewide Lockdown Initiated / Lifted"
"Unknown anomaly at (Location)" (for use during events)

Adds more specific locations as options for the intercom system

Research Offices
HCZ/LCZ/Floor 3 Electrical Centre
Class D Containment
Maintenance Tunnels
Surface Guard Towers

**Comment by MistJules** [comment]
Adding this one here as it is the same idea...

Suggestion: https://www.civilgamers.com/community/threads/shelter-evacuation-announcement.10859/

**Comment by JoshuaLeivers** [comment]
Would be good to also have AA authed/de-authed be possible lines

**Comment by McYeke** [comment]
Unable to facilitate development time - may be revisited in the future, at this time no longer needed.
