### ISSUE TITLE
Medical XP Tree

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#272]
https://www.civilgamers.com/community/threads/add-a-medical-experience-branch.9836/#post-61123

Feature Specification:

A new skill tree for medical only to try and increase the quality of roleplay provided by medical personnel and avoid players from harvesting food to get to a CL3 medical job bypassing any progression.

This would create a further addition to https://github.com/civilnetworks/SCP_Public_Development/issues/267 and give medical XP for specific medical actions as opposed to the generic support XP, assisting with the feeling of progression.

**Comment by ghost** [comment]
Requires re-review

**Comment by auburncivilnetworks** [comment]
closed as unneeded
