### ISSUE TITLE
Cooking EXP Values

### ISSUE THREAD

**Issue by MistJules** [civilnetworks-projects/SCP_Public_Development#273]
Suggestion: https://www.civilgamers.com/community/threads/cooking-suggestion.9187/

The EXP values from cooking different meals need to be looked at and seeing where EXP payouts can be raised to make the system better for players who are trying to raise their cooking skill.

**Comment by ghost** [comment]
Requires re-review (old ticket).

**Comment by auburncivilnetworks** [comment]
reviewed by Content, Determined to be not needed
