### ISSUE TITLE
D-Block - Players cannot hear you beyond the fence of watchtower

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#284]
![image](https://user-images.githubusercontent.com/29537551/209473183-5a4fd89a-ac26-49b5-832c-e995776267eb.png)

Players are unable to communicate with D-Class due to the fact the voice is cut out due to interreference from the railing.

**Comment by cloakical** [comment]
@Freezgam03

**Comment by Freezgam03** [comment]
Would need to figure out first why this is happening.

**Comment by JoshuaLeivers** [comment]
All props are completely opaque to whatever decides the voice transmission range. If you stand on the other side of a chain link fence e.g. in LHCZ Maintenance Room #2, you can't be heard via voice from a foot away.

Same thing with any brushes, e.g. you can't be heard via voice chat through a window at all.

**Comment by Freezgam03** [comment]
@ventz-lgtm Probably best to debug this in combination with you, since you made some changes to the voice chat system in terms of how it detects walls etc. So maybe something went wrong there with fences and so on.
