### ISSUE TITLE
SCP-457 - Kills are not registered from 457 resulting in no XP / Killcam

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#286]
Whenever a player is killed from the fire of SCP-457 the XP does not count towards him during a breach and anyone who has a killcam is unable to have it played if they are SCP-457.

Players do get XP for igniting but kills are counted as suicides

**Comment by McYeke** [comment]
Further Addition: Reported kills from SCP-457 do not count to achievements

**Comment by cloakical** [comment]
Reported as fixed by content team
