### ISSUE TITLE
Vchat - Some players after typing a message will randomly send "0" in chat

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#287]
https://user-images.githubusercontent.com/29537551/209474216-d962549f-450f-42c9-9c20-e8bcaef94510.mp4

Some players after typing a message with send a "0" in chat which after asking Kvarkar stating "Some addon returning 0 in the playersay hook I guess"

**Comment by Rushi123456** [comment]
Closing this ticket, haven't seen this happen and we had no reports about it for the past few months / year.
