### ISSUE TITLE
Surface Gun dealers and Attachments

### ISSUE THREAD

**Issue by MistJules** [civilnetworks-projects/SCP_Public_Development#294]
Suggestion: https://www.civilgamers.com/community/threads/surface-gun-dealers-sell-attachments.10128/

The idea we came up with is to add and NPC to sell attachments on surface and to add to RP by taking one of the houses in Pinewood and converting it into a for of Gun store so it would likely give more RP to Gun dealers overall.

**Comment by RequisJaquavian** [comment]
This has been done - Ranger Station
