### ISSUE TITLE
VCraft - Chemicals with Damage Over Time instantly kill immortal SCPs

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#300]
Injecting Ethanol into SCPs such as 073 or 2295 will instantly kill them.

Steps to Reproduce
Have someone on an immortal SCP.
Buy ethanol and put it in the injection gun.
Inject the immortal SCP.

Expected Behaviour
Depends on the SCP and damage. If for instance it was 073, the person who injected the chemical would die. If an SCP that has the godmode trait, they would either take a small amount of damage or set them to 1 hp.

Actual Behaviour
All immortal SCPs instantly die.

NOTE: This may work for any effect that is Negative heal value from the chemicals

**Comment by ventz-lgtm** [comment]
Fixed
