### ISSUE TITLE
Add flask and Syringe to MC&D

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks-projects/SCP_Public_Development#307]
Add a flask and Syringe to MC&D's shop to purchase for goods.

**Comment by 0-Marco** [comment]
Do you mean their F4 buying menu @Kw1ll?

**Comment by Kw1ll** [comment]
yes @0-Marco

**Comment by McYeke** [comment]
Has been placed on live - will wait 24 hours to see if any issues arise before closing.

**Comment by McYeke** [comment]
Chemistry sets added to MC&D
