### ISSUE TITLE
VDonations UI Rework

### ISSUE THREAD

**Issue by cloakical** [civilnetworks-projects/SCP_Public_Development#309]
Feature specification:
- Rework the VDonations UI to look like it was made in 2023 and not 2003
- Change color scheme to look more like the new donation panel theme
- Change the current panel category system into a nicer tab-based system which can better handle the amount of items in the donation store expanding
- Proper scaling of UI elements, no elements being cut off like the current donation store has

**Comment by cloakical** [comment]
Assigned 50 GBP bounty

**Comment by ventz-lgtm** [comment]
Done
