### ISSUE TITLE
VDonations - Improved rank upgrade system

### ISSUE THREAD

**Issue by cloakical** [civilnetworks-projects/SCP_Public_Development#310]
Feature specification:
- Improve the rank upgrade system to properly show players the upgrades for their current VIP. Could either be by replacing the ranks tab with a 'rank upgrades' tab after they've purchased a rank, or by graying out the rank they've got after buying a rank and discounting the ranks above their own by the appropriate amount, like in a sale

**Comment by cloakical** [comment]
Assigned 30 GBP bounty

**Comment by ventz-lgtm** [comment]
Done
