### ISSUE TITLE
SCP-079 Heavy Doors hitbox is impossible for SCPs to break

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#315]
Description: The heavy doors leading to SCP-079 are only breakable when the SCP is jumping up and looking down creating impossible inconsistencies opening the door

![image](https://user-images.githubusercontent.com/29537551/212332386-aa9262a1-7ffb-4162-9f62-11bfac0969b8.png)

**Comment by Rushi123456** [comment]
Closing - No longer an issue with the new HCZ rework
