### ISSUE TITLE
Dispenser Pricing is different between US and UK.

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#316]
Description: After dispenser prices on the servers were modified, the UK has retained old prices whereas the US has the newer changes.

Image 1 - UK
![image](https://user-images.githubusercontent.com/29537551/212487314-d6b7de26-dafd-4d1b-921d-b03c0ecf3392.png)

Image 2 - USA
![image](https://user-images.githubusercontent.com/29537551/212487320-2739b2b5-d160-42d8-a137-9b4613d9f852.png)

**Comment by cloakical** [comment]
fixed after restart

**Comment by McYeke** [comment]
@cloakical - Had a look to check this was resolved, they are still differing on both servers, unsure if pushed to live
