### ISSUE TITLE
Removing Posion from CL1 Medics

### ISSUE THREAD

**Issue by MistJules** [civilnetworks-projects/SCP_Public_Development#333]
Suggestion: https://www.civilgamers.com/community/threads/removing-posion-from-cl1-medics-and-only-giving-it-to-cl2-medics.10774/

This suggestion will remove poison from CL1 Medics. And only giving it to the medical jobs that require a license. Giving poison access to a job that you still got to be trained for, but it's not too hard to be trained for, will hopefully stop people playing around with poison needles.

This could be removing their access to the !medic menu or making so you need a license to get items from that menu.

**Comment by McYeke** [comment]
This is in regards to using a medical license to access.

**Comment by ghost** [comment]
Is this ticket still valid?
