### ISSUE TITLE
Renaming Vial Cases

### ISSUE THREAD

**Issue by MistJules** [civilnetworks-projects/SCP_Public_Development#335]
Suggestions: https://www.civilgamers.com/community/threads/the-ability-to-rename-chemical-vile-cases.10816/ 
https://www.civilgamers.com/community/threads/be-able-to-name-the-vial-case-in-your-inventory.9761/

This would let a person be able to rename/label the chemical vial cases they have in their inventory.

**Comment by ghost** [comment]
I believe I discussed this with Ventz a while back and we agreed not to do this, will be closing this.
