### ISSUE TITLE
Omega-1 Model Changes (Needs uploading)

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#346]
Suggestion: https://www.civilgamers.com/community/threads/omega-1-uniform-changes.11114/page-2#post-69271

https://steamcommunity.com/sharedfiles/filedetails/?id=2923969305

Description: The models have already been made - Maybe a jacket issue with the specialist (According to Yeke it is fixable)

**Comment by McYeke** [comment]
@foodeater420 stated there were concerns with the jacket, however can be resolved.

**Comment by RequisJaquavian** [comment]
According to the maker of the models, the issues have been fixed @McYeke @foodeater420

**Comment by RequisJaquavian** [comment]
Models uploaded and updated - Closed
