### ISSUE TITLE
SCP-173 Teleporting to players under liquid anima

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#347]
Description
SCP-173 teleports to players who are under liquid anima, and therefore makes the 173 player stuck on walls, in the air, etc.

Steps to Reproduce

. Breach as 173.
. Spam your left-click as usual to kill players.
. If a player that is under liquid anima is near you, you will tp to them and get stuck.

Expected Behaviour
You shouldn't tp to people you cannot kill 

Actual Behaviour
You tp to players under anima, and get stuck, practically wasting time and losing HP fast

Evidence
https://media.discordapp.net/attachments/1075725139192336465/1075725217105711114/20230216101831_1.jpg?width=1205&height=678

https://media.discordapp.net/attachments/1057771824353640568/1076049290725703721/20230216101735_1.png?width=1339&height=753

**Comment by gnoment** [comment]
Duplicate
