### ISSUE TITLE
When revived in handcuffs, your gun is produced bypassing cuffs

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#348]
Description: When in handcuffs, if you are killed, then revived through defibrillation, you get revived with your gun out but which you can fire, however the game still treats you as cuffed, but unable to break out, leading to confusing situations;

Evidence:
![image](https://user-images.githubusercontent.com/29537551/219879209-36356eea-4097-4284-9740-3f017c895aab.png)

Replication steps:
1. Have a weapon equipped
2. Get handcuffed
3. Get killed (reliable method, using M9k_harpoon)
4. Get revived by defibrilators
5. You are now able to move and shoot, but being bound by handcuffs.

**Comment by CNCanoon** [comment]
To be checked by content to see if this is still an issue.

**Comment by BlueCivilnetwork** [comment]
No longer an issue @CNCanoon .
