### ISSUE TITLE
Administrative ID Cards

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#349]
**Suggestion:** https://www.civilgamers.com/community/threads/add-administrative-id-cards.10619/

An administrative ID is an ID card that authenticates the identity of MTF O-1/A-1 as well as any CL5 personnel when being ID checked, such as during code 1s or HCZ. This is to prevent full names or the knowledge of CL5s being known. This does not replace code words. MTF O-1/A-1 and CL5 personnel will spawn with the administrative ID. The administrative ID cannot be dropped on death, but can be stripped when the interrogation tole is used. The card should simply show their regiment and rank with the text "administrative ID"

**Comment by auburncivilnetworks** [comment]
Closing as unneeded
