### ISSUE TITLE
GM Prop Teleportation

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#350]
**Suggestion:** https://www.civilgamers.com/community/threads/gm-objective-improvements.10096

Allows for teleportation between two points when interacted with. Would save time and resources for GMs to automate the teleportation of users during most events. Have the option of "on contact" and "on interaction," and would teleport the player to the linked teleport.

**Comment by liondadev** [comment]
I'm currently working on this, should be done soon.
