### ISSUE TITLE
GOC Orange Suit Tactical Tablet Addition

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#353]
Suggestion: https://www.civilgamers.com/community/threads/add-goc-orange-suits.10678/
Merged with: https://www.civilgamers.com/community/threads/ungoc-tactical-tablet-addition.11421/

The GOC orange suit is essentially a mech suit that grants the user extra health and armor. The GOC orange suit would be called in like any other airdrop, using the tactical tablet, and should only be used in emergency situations such as surface SCPs or wars. The one to claim the airdrop must be licensed, and will be the one to claim the Orange Suit. The Orange Suit will have it's own job, invisible, just as an SCP. This is to prevent intractable objects from being used. 

These are the specifications:

    1K HP.
    2K armor.
    Regular walk and sprint speed.
    Ammo pack.
    Only deployable by MAJ+
    15M from warfunds.
    License given out by MAJ+ (New license exclusive to GOC, ExoSuit license) and only usable by license holder.
    Mauler given as only weapon.
    Cannot pick up other weapons (SCP-like inability, can still access doors)
    No AA.
    3 hour cooldown (upon orange suit death)
    ERT immunity (nerve gas, infection, etc.)
    On death, combust like a vehicle. No damage. (Alternative is ignite the ragdoll)
    Cannot be "one-shot" by 8854, although damaged. 100 damage dealt
    Unaffected by 323.
    Cannot have more than one spawned in.
    FearRP would be a 3:1 ratio (surrounded).
    Cannot be fractured.

Model already exists: models/player/cheddar/suit/orange_suit/orangesuit.mdl
Scale up to 1.2x

**Comment by auburncivilnetworks** [comment]
closing as orange suit has since been implemented into the server.
