### ISSUE TITLE
Custody officer arrest permissions - Ethics/Omega-1

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#354]
**Title of the Bug**
Custody officer arrest permissions - Ethics/O-1

**Description**
Omega-1 & Ethics Committee unable to arrest using the custody officer

**Steps to Reproduce**
1. Cuff someone
2. Attempt to arrest them while on job as a: Ethics Member or Omega-1.

**Expected Behavior**
Ethics Members and Omega-1 to be able to arrest using the custody officer, similarly to how Alpha-1, Overseer Assistants and Overseers can.

**Actual Behavior**
Ethics Members and Omega-1 cannot arrest using the custody officer.

**Evidence**
Says: "You cannot make arrests"

**Comment by gnoment** [comment]
Isn't this SA configuration @RequisJaquavian

**Comment by RequisJaquavian** [comment]
According to @McYeke changing arrest permissions isn't. @gnoment

**Comment by RequisJaquavian** [comment]
Resolved. Been made an actual thing through VJOB.
