### ISSUE TITLE
CloakCredits improvements

### ISSUE THREAD

**Issue by cloakical** [civilnetworks-projects/SCP_Public_Development#356]
CloakCredits is an addon that was originally made for the end of the NATO vs USSR campaign on MilitaryRP in mid-2022. It allows you to create cinematic credit sequences, with music, images & text, with animations such as scrolling, fade-in/fade-out, etc.

Currently this addon is not in use on SCP-RP (and is not in use very often on MilitaryRP), as creating new sequences requires someone with FTP access to update the config.

If we had a configurable in-game menu which GMs and SL had access to, then we would be able to use this addon much more frequently - e.g. to show players storyboards for events, with hand-drawn art and custom lore. This would improve our events significantly. We should also add a way to only make nearby players / a group of players see the credit sequence, as currently you can only play it for all players online at once.

Feature specification:
- Update credit sequences so that they can be configured using an in-game menu and saved into a file
- Should maintain cross-compatibility with the existing method of configuration (i.e. both FTP and in-game configuration should be valid ways of creating credit sequences)
- Add a command that allows you to play the credit sequence for every player in a given radius
- Add a command that allows you to play the credit sequence for a selected group of players
- Change music config from referencing a mp3 on the server to a referencing an mp3 by URL

**Comment by metropolitan24** [comment]
@AlphaToon It looks like you are assigned to this, has this been worked on at all or can I move this back into the backlog?

**Comment by AlphaToon** [comment]
@metropolitan24 Yes it has been worked on. Have to start on my code review for it though.
