### ISSUE TITLE
vguns - P320 pistol not aligned

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#363]
**Description**
P320 Pistol crosshairs are not centred when ADS.

**Steps to Reproduce**
1. Take out the P320
2. Aim Down Sights
3. Crosshair not in the centre.

**Expected Behaviour**
Crosshair should be centred

**Actual Behaviour**
It isn't centred
![image](https://user-images.githubusercontent.com/29537551/225710448-7331b5d0-def0-4710-9afd-52849e8850c3.png)
![image](https://user-images.githubusercontent.com/29537551/225710474-d1b716ea-d6a2-4b6f-bddb-31d2f7097595.png)

**Comment by RequisJaquavian** [comment]
This has been fixed
