### ISSUE TITLE
Add Shawarma to Recipe List

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#365]
Suggestion: https://www.civilgamers.com/community/threads/add-shawarma-to-the-game.12527/

Perfect shawarma adds 26 hunger, 5hp and 7 speed.
Amazing shawarma adds 24 hunger, 4hp, and 5 speed.
Good shawarma adds 22 hunger, 3hp, and 4 speed.
average shawarma adds 20 hunger, 2hp and 4 speed.
bad shawarma adds 14 hunger, 0hp, and 1 speed.
terrible shawarma adds 7 hunger, 0hp, and 1 speed

**Comment by RequisJaquavian** [comment]
Done.
