### ISSUE TITLE
Make 7722 Sampleable

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#366]
Suggestion: https://www.civilgamers.com/community/threads/sample-able-7722.12402/

Adds the ability to sample 7722
chemical 1: Living metal, when taken your armor will regenerate 1 point/s but your speed will slow, effect lasts 60 seconds

chemical 2: Metallic Blood, when taken you you will heal 25 Health and Armour

**Comment by Rushi123456** [comment]
This will be done whenever the chemical rework is done

**Comment by McYeke** [comment]
Closed to SSL discretion
