### ISSUE TITLE
Add Effects to Hume Fields

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#370]
**Suggestion:** https://www.civilgamers.com/community/threads/make-hume-fields-do-something-interesting.12989/

Add "side effects" to entering hume fields for prolonged amounts of time. For example, over time start permanently disorienting a player's vision until "healed" by medical, "silent death" if stood in one while closing, and chances to randomly gain anomalous properties (such as those found in inanimate. Insanity, healing, etc.).

**Comment by auburncivilnetworks** [comment]
Closing as Hume bubbles already have effects
