### ISSUE TITLE
VComputers Document Quality of Life changes

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#371]
**Suggestion:** https://www.civilgamers.com/community/threads/clipboard-document-qol-improvements.13081/

Add hyperlinks, or just shortcuts, to go to certain pages when clicking on an element, like a table of contents.

**Comment by LordMirai** [comment]
Actual work underway:

~~- Fix non-functional memetic kill agent~~ delayed

- QoL changes of https://civilgamers.com/community/threads/clipboard-document-qol-improvements.13081/

**Comment by LordMirai** [comment]
- First/Last page buttons (Displayed as  <</>>)
- "Jump to" dropdown button to select page
- Duplicate page button
- Page hyperlinks
- Checkbox switch for in-menu microphone activation
- Document scanning
