### ISSUE TITLE
Make Intelligence Operative/Agent 100 Armor

### ISSUE THREAD

**Issue by Civil-ZeusRose** [civilnetworks-projects/SCP_Public_Development#373]
**What does this suggestion change/add/remove:**
The proposed suggestion aims to introduce a modification to the existing gameplay mechanics of the game, specifically by adding 50 additional armor points to the Intelligence Operative and Agent roles upon spawning.

**Possible Positives of the suggestion (At least 2):**
This proposal appears to be a pragmatic solution, grounded in our operatives/agents being equipped with full vests. It seems incongruous to spawn with only 50 armor in light of this. Implementing this change would provide a more equitable playing field, evening out the advantages enjoyed by CI operatives who currently spawn with 100 armor.

**Possible Negatives of the suggestion:**
One potential drawback to this decision is the potential for discontent from our competitors at CI. This is due to the fact that our dominance in the market may be further solidified, potentially leading to an even more significant competitive disadvantage for them.

**Based on the Positives & Negatives, why should this suggestion be accepted:**
Because it is necessary and self-evident, it balances RP and gives everyone a fair shot.

**Comment by RequisJaquavian** [comment]
Is this a suggestion or is this to be done @Civil-ZeusRose ? For DEA

**Comment by Rushi123456** [comment]
Will be closing this, as the Content Team feels this is no longer required with the new DEA update.
