### ISSUE TITLE
Update CI Rank

### ISSUE THREAD

**Issue by InveII** [civilnetworks-projects/SCP_Public_Development#376]
Change the rank requirement for CI tech expert to CI-Alpha instead of CI-Beta
Currently the class holds only a Level 2 card, so it'd make more sense for it to be reduced to Alpha.

This needs to be discussed with CI commanders by SSL first.

https://www.civilgamers.com/community/threads/ci-tech-reduced-to-alpha-rank.13499/

**Comment by RequisJaquavian** [comment]
Changed to CI-Alpha rank requirement.
