### ISSUE TITLE
Make Type-Blue selected by queue

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#387]
https://www.civilgamers.com/community/threads/change-how-the-new-type-blue-d-class-job-is-chosen.13777/

**Description:** Make Type-Blue selected by queue, just how SCP-8854 and SCP-323 work. Essentially, players would press the Queue button and then it would choose a random player selected after awhile.

**Comment by auburncivilnetworks** [comment]
Closing as unneeded
