### ISSUE TITLE
Add logs to keep track of what is placed inside of Substance Storages/Fridges

### ISSUE THREAD

**Issue by L-Saint** [civilnetworks-projects/SCP_Public_Development#392]
Description:
Add a new section to the logs to show what is placed inside of a fridge. This would include the type of container, the substance inside and how much was inside

Suggestion:
https://www.civilgamers.com/community/threads/log-content-of-items-placed-in-fridges-in-logs.13975/#post-89241

**Comment by McYeke** [comment]
Completed
