### ISSUE TITLE
Scrap Dealer Delay May Be Seconds Long

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#393]
The D-Class scrap dealer, at random, may have windows of only seconds where it does not offer weapons. For example, it'll close and re-open within a few seconds. Picture:

![image](https://user-images.githubusercontent.com/67607329/233385731-4b9640fd-e0b1-4cb3-9668-e80170e26352.png)

**Comment by CNCanoon** [comment]
To check to see if this is still an issue.
