### ISSUE TITLE
Killhouse times being recorded in-game

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#397]
https://www.civilgamers.com/community/threads/killhouse-times-being-recorded-in-game.14041/#post-90241

This will add a button and then a screen on the killhouse that would stop the timer until the button is pressed again or whenever Killhouse is completed.

**Comment by Freezgam03** [comment]
Doing this through the map is inefficient and could result in lag affecting the time. So you would be better off doing it through lua. I can add hooks though for when the course is started and ended.

**Comment by Freezgam03** [comment]
**For Programmers:**

I added 2 hooks for when it begins and ends, so you can easily time it without having to create zones or anything.

killhouse.coursestart
killhouse.courseend
