### ISSUE TITLE
SCP-106 changes

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#40]
https://www.civilgamers.com/community/threads/misc-abilities-scps.3923/

**Comment by Kw1ll** [comment]
Add way to TP to his own dimension and back
Add teleport marker such as that in SCP SL where you can tp back to
Make it so the sacrifice in 106 CC gets a fracture and put in bleeding state
When people die in 106 dimension, 106 gets XP and added kills to the k/d on tab menu

**Comment by ghost** [comment]
Requires re-review (old ticket).

**Comment by auburncivilnetworks** [comment]
Not needed, outdated ticket
