### ISSUE TITLE
Surface jobs / locations improvements

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#405]
https://www.civilgamers.com/community/threads/civilian-surface-overhaul-for-better-relations-between-foundation-chaos-insurgency-and-goc.11956/page-2#posts

**The following points were accepted:** 
- Add one more slot to Ranger;
- Add a lab to Pinewood hospital (where medics spawn)
- Give MC&D a house (maybe in lakehouse);
- Give Rangers elastics restraints to make arrests easier
- Give !medic to surface medics.

**Comment by McYeke** [comment]
@Rushi123456 - !medic is already implemented after review and does not need work on this
