### ISSUE TITLE
License Changes

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#408]
**Suggestion:** https://www.civilgamers.com/community/threads/license-addition-some-changes.14575/
Change the required regiments and groups to provide licenses to the following:
All MTF - All Driving Licenses
E-11 - Heavy Weapons
Nu-7, DEA - Sniper
GENSEC - RRT, Heavy Weapons​

This would restrict the licenses to be given by these groups within the Foundation only. This requires players to interact with other regiments during their trainings for certain licenses.

**Comment by McYeke** [comment]
This is an IC Training policy, not for Staff.
