### ISSUE TITLE
Add Drone Jammers to GOC and CI

### ISSUE THREAD

**Issue by gnoment** [civilnetworks-projects/SCP_Public_Development#411]
**Suggestion:** https://www.civilgamers.com/community/threads/dea-drones-spying-without-any-jammers-to-counter.14373/
This would add drone jammers to GOC and CI. Should be added once jammers are modified to be more useful than it's current state.

**Comment by Rushi123456** [comment]
Will be closing this as this won't be necessary (since we do not use drones anymore)
