### ISSUE TITLE
Jobbans not working

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#413]
Jobbans not working

**Description**
Ethics Committee can not job ban - similar issue to the Site Managers not job banning, but that was a fixed issue.

TEAM_ETHICS_COMMITTEE_MEMBER

**Comment by McYeke** [comment]
Will look into this later today.

**Comment by McYeke** [comment]
After review this ticket is actually pertaining to job approvals not job bans, ethics are able to job ban.

**Comment by McYeke** [comment]
Believe this to be resolved.
