### ISSUE TITLE
SCP - 978 "Desire Camera"

### ISSUE THREAD

**Issue by Kranted** [civilnetworks-projects/SCP_Public_Development#435]
Suggestion : https://www.civilgamers.com/community/threads/scp-978-the-desire-camera.15468/

Transcript :

What does this suggestion change/add/remove:
A new SCP in LCZ inanimate objects room, SCP-978 ([link to the scp article](https://scp-wiki.wikidot.com/scp-978)) "The Desire Camera".
It is closed by a LVL 2 clearance door.

How will it work in the server:
When you grab it and take a picture of a player, the camera will print out a photograph of what that player would want to do. (their desire for their current job.)
Now for the server to grab the photograph, it will grab it from that player's F4 menu in the "SCP-978 outputs" tab.
1685703706400.png
of course, people can designate each of their images to each of their jobs. (each job has its own output slot)
the process of how they upload images is through imgur/upload.

If a player got screenshotted though SCP-978 and they don't have an image saved (for that particular job they are playing as),
the output will just show a normal screenshot, as if the camera is just a normal camera.

Possible Positives of the suggestion (At least 2):
+New SCP in LCZ inanimate.
+Almost Endless possibilities for outputs.
+New way to psychologically evaluate someone in RP.

Possible Negatives of the suggestion:
-Might be hard to code. but it should take the same code from the clipboards "upload image" button.
-New thing for new players to be bothered with.
-If left Unmoderated, could lead to a cesspool of ooc memes, nsfw images or Fail RP violations.

Based on the Positives & Negatives, why should this suggestion be accepted:
Upon close inspection of this suggestion, while the idea is good, it might be poorly executed due to the playerbase, because this SCP depends on the players' creative ways of depicting their desires through images. but I think giving this suggestion a chance would give out the most hilarious RP scenarios due to its nature. furthermore, due to its limitless potential on research, there will be an uptick on research personnel.
![1685703706400](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/112734279/d64dc8f3-09c4-4c10-a970-2192417ce718)

**Comment by ghost** [comment]
Moving this to Revision Required as it seems like this would be incredibly difficult and slightly complex to implement well. Feedback from others is appreciated on this.

**Comment by auburncivilnetworks** [comment]
Closing as unneeded
