### ISSUE TITLE
Document Scanning

### ISSUE THREAD

**Issue by Kranted** [civilnetworks-projects/SCP_Public_Development#436]
https://www.civilgamers.com/community/threads/document-scanning.15398/

Transcript : 
What does this suggestion change/add/remove:
Add another option at printer, that lets you scan a held document onto your clipboard, preferably including signatures.

Possible Positives of the suggestion (At least 2):
Makes it easier to distribute informational documents, and in the case of researchers getting tests approved, would allow them to store the signature.

Possible Negatives of the suggestion:
Can't think of any.

Based on the Positives & Negatives, why should this suggestion be accepted:
It would be some nice quality of life, and I'm sure at least the scanning document to clipboard part would be an easy addition. As for keeping signatures when scanned, this would be extremely nice, but not necessary.

**Comment by LordMirai** [comment]
done through https://github.com/civilnetworks-projects/SCP_Public_Development/issues/371
