### ISSUE TITLE
Vchat messages severely drain FPS

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#439]
If you watch your FPS counter, and type a few messages in chat, your FPS will go down by quite a bit.

From my tests, just 5 messages were enough for me to drop from 120 FPS to around 90-100 FPS on the test server.

**Comment by CNCanoon** [comment]
To check to see if this is still an issue.

**Comment by BlueCivilnetwork** [comment]
Still an Issue @CNCanoon .
