### ISSUE TITLE
SCP-173 not able to move due to dead players

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#446]
**Description**
SCP-173 is not able to move and says he's been seen, because of dead players that are looking at him.

**Steps to Reproduce**
1. Go as SCP-173
2. Go nearby a player that is dead
3. You won't be able to move

**Expected Behavior**
Dead players would not count towards people that "see" SCP-173, therefore he could move

**Actual Behavior**
SCP-173 won't be able to move due to the dead players.

**Evidence**
https://streamable.com/7k7kl4

**Comment by GarrySwepman** [comment]
Maybe SCP-173 is just afraid of ghosts

**Comment by CNCanoon** [comment]
To check to see if this is still an issue.

**Comment by BlueCivilnetwork** [comment]
No longer an issue @CNCanoon .
