### ISSUE TITLE
Change / tone down some of the infections symptoms / effects (flashing screen)

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#451]
**Description:** As the description says, any infections that has the flashing screen (bacterial infections, sinus infection, e.t.c.) should be tone down or just changed. This is due to the fact that it actually causes IRL headache (too immersive!).

**Comment by GarrySwepman** [comment]
Well hey the devs certainly did a good job with immersion!
