### ISSUE TITLE
vwar / vjobeditor - Chat Comms Channel doesn't need "/"

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#452]
**Description**
Whenever you make a custom comms on vjobeditor, it doesn't need to have a / before the message. i.e.: doing "gensec is cool" will put "is cool" in gensec comms.

**Steps to Reproduce**
1. Make a comms in vjobeditor
2. type the name of comms without the / at the start
3. it will type in comms

**Expected Behavior**
Essentially, what is suppose to happen is the same as /c , /c1 , /c2 and e.t.c, if you don't put the "/" at the start, it won't type in comms. 

**Actual Behavior**
Not using the "/" at the start will still type in the custom comms, so long the custom comms are made in vjobeditor.

**Comment by ventz-lgtm** [comment]
Fixed
