### ISSUE TITLE
Allow Site Administration & Site Command to cut foundation personnel comms

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#455]
https://www.civilgamers.com/community/threads/cut-comms.17303/page-2#post-115219

**Description:** This suggestion would allow for Site Administration & Site Command to have an option on the Personnel Tablet to cut other individual foundation personnel comms. IC Policies will be made whenever this is done.

**Comment by GarrySwepman** [comment]
I think this should be restricted to Level 5 Job's

**Comment by ghost** [comment]
Completed as part of the Chemical Weaponry update a few months back.
