### ISSUE TITLE
Show how much time you have on a job

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#463]
This suggestion is a overhall of the vtime system to allow it to keep track of time spent on a specific jobs. 

When on a job you would be able to access the vtime menu using /vtime and it would open up the interface, but have a new tab for time spent on the job you are currently on using the standard vtime format.

https://www.civilgamers.com/community/threads/show-how-much-time-you-have-on-jobs.18542/

**Comment by auburncivilnetworks** [comment]
Closing as unneeded, and would require too much server resources to record and store all the new data
