### ISSUE TITLE
Adding the gamemaster rank to the tab menu

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#464]
This woudl add the ULX rank to gamemasters tab menu like it is with staff. This will make at easer to find gamemasters as they would just have to look at the tab menu instead of having to click on every name looking for the rank

https://www.civilgamers.com/community/threads/tag-beside-your-name-on-tab-menu-for-gamemaster.19174/

**Comment by AlphaToon** [comment]
Change is now live
