### ISSUE TITLE
E-11 Secondary spawn

### ISSUE THREAD

**Issue by TGiovr** [civilnetworks-projects/SCP_Public_Development#466]
https://www.civilgamers.com/community/threads/e-11-garage-spawn.19425/page-3#post-131478
https://www.civilgamers.com/community/threads/e11-spawn-rework.18686/#post-124857
E-11 Has recently had a lot of complaints about the spawn issues due to it taking an extended amount of time for an E11 member to run all the way back to LCZ if they die up there during a breach, an attempt was made to add a secondary spawn in security sector however it was spawning them in unintended locations. Ventz said it was because it was using the large spawn radius of the MRP FOB spawn, so a new one would need to be made.

**Comment by Rushi123456** [comment]
Closing this as there is already a ticket about it.
