### ISSUE TITLE
ERT being able to heal up to 600HP

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#467]
https://www.civilgamers.com/community/threads/allow-ert-to-heal-back-to-600-hp.19647/

**Description**: Essentially, ERT is only able to heal to 100 HP (unsure if it's because of the medkit itself, or ERT max HP not being set to 600?).

**Comment by auburncivilnetworks** [comment]
Duplicate of https://github.com/civilnetworks-projects/SCP_Public_Development/issues/684
