### ISSUE TITLE
Allow Major+ to accept regiment transfer requests

### ISSUE THREAD

**Issue by TGiovr** [civilnetworks-projects/SCP_Public_Development#477]
**Forum link** https://www.civilgamers.com/community/threads/allow-certain-ranks-to-accept-and-create-battalion-transfer-requests.20462/

**Feature description**
Allows Major+ and equivalent ranks of CI and GOC to be able to accept transfers into their regiment.

**Comment by HerrKvarkar** [comment]
Implemented on MRP, will add to SCP branch soon
