### ISSUE TITLE
Add a search bar for names in the regiment transfer area

### ISSUE THREAD

**Issue by TGiovr** [civilnetworks-projects/SCP_Public_Development#479]
**Forum link**  https://www.civilgamers.com/community/threads/new-way-to-reg-transfer.20518/#post-138545

**Enhancement description**
would add a search bar to the request player transfer screen to make finding the player needing to be transferred easier and faster.

**Comment by HerrKvarkar** [comment]
Implemented on MRP, will add to SCP branch soon
