### ISSUE TITLE
SCP Re-containment announcement in chat doesn't say which SCP was contained.

### ISSUE THREAD

**Issue by emilsnat** [civilnetworks-projects/SCP_Public_Development#482]
![Image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/129634855/4610082d-d569-4b17-b603-acf294c0bed2)

Although the notification says the name of the SCP which was contained, the text chat appears to be broken and has a blank space where the scp name should be.

**Comment by CNCanoon** [comment]
I believed this is resolved, but to be checked.

**Comment by BlueCivilnetwork** [comment]
This is still an issue @CNCanoon .
