### ISSUE TITLE
GMTP - Click to tp

### ISSUE THREAD

**Issue by ventz-lgtm** [civilnetworks-projects/SCP_Public_Development#483]
A SWEP should be made to TP those who are clicked on to a certain GMTP event node(s), so a GM can easily send people to a gmtp location that they have already configured. 

Reload should send the swep holder to the tp location(s).

 There should be a way to easily swap between different tp points, EG if a GM wants to send one group to one location and a second group to a different one, either they could bind a second location to right click, or potentially a way to quickly cycle through different positions.

Original ticket: https://github.com/civilnetworks-projects/SCP_Public_Development/issues/350
Whoever does this will need access to the github repo

**Comment by liondadev** [comment]
For whoever does this: there's a function to perform a teleport.

See gmtp:PerformTeleport(groupId: string, ply: Player) in `lua/gmtp/core/sv_teleport.lua`

**Comment by liondadev** [comment]
Pretty sure this is done, I'll bring it up at the dev meeting.

**Comment by liondadev** [comment]
Blocked by #535 -- want to test both at the same time
