### ISSUE TITLE
ls_thirdperson convar is a float instead of `0` or `1`

### ISSUE THREAD

**Issue by liondadev** [civilnetworks-projects/SCP_Public_Development#504]
Discord Ticket Link: https://discord.com/channels/847587034792460328/1193421603938259005

### Details
From bug report ticket: `This is a QoL type of "bug" (rather, semantic error), not a big one, but one that is a bit annoying. The convar ``ls_thirdperson`` accepts floating-point numbers, despite being quite clearly a boolean.`

### Steps to reproduce
Set `ls_thirdperson` to something besides `1` or `0`, like `0.25`.

**Comment by emilsnat** [comment]
Not a bug
