### ISSUE TITLE
Internal Affairs Arrest Records

### ISSUE THREAD

**Issue by Rushi123456** [civilnetworks-projects/SCP_Public_Development#505]
**Forum link** 
https://www.civilgamers.com/community/threads/ia-arrest-record.20470/

**Enhancement description**
This enhancements would allow Internal Affairs, Site Administration, O5 and Ethics to check Arrest Records of other players of the same faction.

I believe this is already something that is on MRP, which is why this is on enhancements :)

**Specification**
Some jobs would have their records excluded from being viewed by Internal Affairs, such as D-Class and Internal Security Department, unless the person viewing it is a Clearance 4 personnel.

**Comment by auburncivilnetworks** [comment]
Closing as unneeded, and would create issues with how characters are treated in RP in the server.
