### ISSUE TITLE
Add the Other Variants of NVGS

### ISSUE THREAD

**Issue by JackKincaed** [civilnetworks-projects/SCP_Public_Development#506]
(https://www.civilgamers.com/community/threads/add-the-other-variants-of-nvgs.21339/)

Description:
Adding the other variants of the NVGs within the addon into the pool.

Specification:
The other NVGs are to be added for either more options for people to use or accessibility for people who may not have a comfortable experience with the green ones we already have. They may be picked up through the armory or a new small box that would have all of the NVGs in a menu for selection (Maybe Including thermals). Also remove any black bars that surround any of the other NVGs/THERMALS.

**Comment by KaptianCore** [comment]
Thermals are quite powerful weren't they removed from GOC because of that?

**Comment by JackKincaed** [comment]
No clue since I was not part of the server back then but we can either allow all GOIs to use thermals or we can just forgo thermals altogether. Thermals weren't the main focus so we can make do with or without.
