### ISSUE TITLE
AMM - Morphine syringe

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#510]
**Enhancement description**
Provide a use to the Advanced Medical Mod's morphine syringe following from the change to limit it to unholsterable

the idea is to make the morphine syringe when used provide a small boost in speed 5% and allow users to walk on a fractured leg temporarily curing it or curing their arms temporarily so they can hold key items such as 2 handed guns or keycards.

**Specification**
When injecting the morphine syringe, the idea is to temporarily give the following effects.

- 5% speed boost for duration
- Temporarily fix fractures for a period of 2 minutes before needing medical attention to permenantly fix it.

This will work on the Advanced Medical Mod's "syringe_morphine"

**Comment by auburncivilnetworks** [comment]
also put it in dispensors at 5m cooldown so people can get it out on the fly
