### ISSUE TITLE
Hacking Alerts QoL/Improvements.

### ISSUE THREAD

**Issue by JackKincaed** [civilnetworks-projects/SCP_Public_Development#517]
(https://www.civilgamers.com/community/threads/downtime-hacking-alerts-improvement.21887/)

Immediate change: Add the SCP hacking alert system to SCU 

Long-term: Combative jobs getting the alerts in the absence of active E-11 Players.

**Comment by auburncivilnetworks** [comment]
@ellie00001 FTP change!

**Comment by McYeke** [comment]
@auburncivilnetworks Was completed by Luft 

https://discord.com/channels/847587034792460328/847589320092942386/1206342147171684452
