### ISSUE TITLE
Giving CL4 jobs prop placement swep similar to the quarantine placer.

### ISSUE THREAD

**Issue by JackKincaed** [civilnetworks-projects/SCP_Public_Development#518]
(https://www.civilgamers.com/community/threads/rp-items-placer-tool.21926/)

Every department CL4 job would have a department-specific prop they can place like a police fence for GSD for example.

**Comment by KaptianCore** [comment]
Closing as Duplicate of https://github.com/civilnetworks-projects/SCP_Public_Development/issues/520
