### ISSUE TITLE
Chef NPC inventory Unlinking.

### ISSUE THREAD

**Issue by JackKincaed** [civilnetworks-projects/SCP_Public_Development#523]
(https://www.civilgamers.com/community/threads/remove-the-link-between-chef-npcs-and-increase-the-restock-timer-usa.21698/)

Unlink the chefs so that whatever they have in stock is not all shared across all the NPCs.

e.g. If you buy all the MREs from the GOC Chef, The Foundation chef will run out of MREs. This suggestion wishes to unlink them so every chef has their own stockpile.

**Comment by auburncivilnetworks** [comment]
Closing as unneeded
