### ISSUE TITLE
MTF COs (LT+) unable to kick members from their regiment

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#525]
**Description**
Non Staff MTF LT+ cannot remove people from their own regiments. They have to get a staff to remove them for them.

**How to Replicate**
- Set yourself as LT+ in any regiment
- Remove your staff rank (Do this with another Sr Admin so they can re-add you to your staff rank)
- Attempt to remove someone from your regiment

**Comment by CNCanoon** [comment]
I believe this is resolved ,but to be checked by Content.

**Comment by BlueCivilnetwork** [comment]
Still an issue @CNCanoon .
