### ISSUE TITLE
Medical Chemist Broken

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#545]
### Description
About 2 months ago, we attempted to change the name of the Foundation Medical Department's Chemist job to Pharmacist, better fitting their role working with cures and medicine.
This broke the job and split it into a duplicate, with both jobs existing concurrently, and the previous Chemist job unable to be edited as it is in jobs.lua

There are two solutions:
1. Remove the old chemist job.
2. Remove the new Pharmacist Job, and rename the old Chemist job to Pharmacist. Then make the job editable in VJobEditor.

**Comment by McYeke** [comment]
@auburncivilnetworks Is this broken in a sense the Pharmacists cannot make cures or?

**Comment by auburncivilnetworks** [comment]
@McYeke no, they both have access to the VIP Vcraft chemistry items. Its just we have Chemist and Pharmacist at the same time, when chemist was just supposed to be renamed to pharmacist. Since Chemist is configured in jobs.lua we can't do anything to it. We just need chemist removed, since Pharmacist does everything chemist does.

**Comment by Raptor731** [comment]
Also chemist is unable to spawn in vcraft chemistry things

**Comment by auburncivilnetworks** [comment]
Addition: SCP Foundation Chef also needs to be fixed as it is defined in jobs.lua and cannot be edited using vjobeditor
