### ISSUE TITLE
When opening chat, your hand does not lift up to your ear

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#549]
### Description
After the recent update with Vchat, It has caused the player model to no longer put their hand up to their ear to indicate whether if they are talking in chat or not, This is not a PAC3 issue since I have already tested this.

### Steps to Reproduce
Open chat and your hand will not lift up

### Expected Behaviour
your hand should lift up to your ear

### Actual Behaviour
It Doesn't

**Comment by ghost** [comment]
Moved from critical to low.

**Comment by CNCanoon** [comment]
To be checked by Content.

**Comment by CNCanoon** [comment]
Appears to be fixed.
