### ISSUE TITLE
079 Breach Queue Oddities

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#552]
### Description
SCP-079 queue seems to be broken.

### Steps to Reproduce
Flag on to SCP-079 (Might only be the case on low SCP numbers flagged on or below 60 players)

### Expected Behaviour
You will join the queue in the next available slot.

### Actual Behaviour
You may be in the 3rd wave of breaches despite only 1 or even no SCPs breaching in the queue before you. Leaving you with a potential 14h+ queue time. If another SCP flags on they will be put in the first slot, therefor being in front of you. I don't believe this is intended.

### Evidence
https://medal.tv/games/garrys-mod/clips/1Yt1njTbzcwTqV/d1337C0CtsSC?invite=cr-MSxGQnYsMTcwNTg0ODU2LA
We tried having different people flag on and off and having another SCP flag on before/after us yet it still resulted in this. Ellie was also present for most of this.

**Comment by JacubRSTNC** [comment]
Intended feature
