### ISSUE TITLE
Event Team Immortality

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#553]
### Description
People on the job can not take any damage unless it is falling damage.

### Steps to Reproduce
1. Climb onto the event character or event team
2. Have someone shoot you

### Expected Behaviour
Take damage

### Actual Behaviour
Nothing Happens

### Evidence
https://medal.tv/games/garrys-mod/clips/1YiNlBu0qaQvvh/SfbSiAIJ1Q3S?invite=cr-MSxxemwsMTcyMjM0MTk3LA?mobilebypass=true

**Comment by ellie00001** [comment]
This is sorted - the SCP Ignore option in vjobeditor was causing this
