### ISSUE TITLE
ERT die on deployment

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#554]
### Description
ERT die when being brought in with the helicopter. According to the ticket made, multiple people have had this problem.

### Steps to Reproduce
1. Agree to ERT deployment
2. Deploy as ERT
3. Be seated on the far side of the helicopter

### Expected Behaviour
The animation completes and you are dropped to the surface in front of the base

### Actual Behaviour
You get downed on spawn, leading to your hp being below 100 as soon as you deploy (if people revive you straight away)

### Evidence
https://medal.tv/games/garrys-mod/clips/1OP8yOtwNO-JZv/d1337ae2EPsZ?invite=cr-MSxQMGEsODkzNTQ4Njgs

**Comment by CNCanoon** [comment]
To be checked by Content.

**Comment by CNCanoon** [comment]
tested, does not appear to be an issue anymore.
