### ISSUE TITLE
Add the percentage of how many players have an achievement.

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#557]
(https://www.civilgamers.com/community/threads/let-us-preview-the-attainment-rate-of-the-achievements-in-the-f4-menu.23142/#post-162625)

**Enhancement description**
Would add to the achievement tab of the F4 menu a percentage of how many players have said achievement 

**Specification**
More granular list of individual mechanics or details about the enhancement
Would 
![image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/136268820/d7001822-0279-4a76-ab79-ea1634dd018d)

**Comment by HerrKvarkar** [comment]
@Raptor731 This is already there?

**Comment by Raptor731** [comment]
Im being a goober

**Comment by Raptor731** [comment]
It only appears once you get said achievement @RealAtomar this is for it to appear before you achieve it
