### ISSUE TITLE
New VChat buttons don't appear on US or UK.

### ISSUE THREAD

**Issue by liondadev** [civilnetworks-projects/SCP_Public_Development#561]
Forum post link: [N/A](https://discord.com/channels/577041202684231710/1218382947888140358)

### Details
The new VChat buttons that kvarkar added don't appear.

Ref: https://i.imgur.com/DQNXtd0.png

### Steps to reproduce
1. Open Chat
2. Right Click A Message
3. Be Disapointed

**Comment by ellie00001** [comment]
They appear now.
