### ISSUE TITLE
Medical Chemist doesn't have access to chemical equipment

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#588]
### Details
Medical chemist does not have access to the chemical equipment

### Steps to reproduce
Flag onto medical chemist
press F4
no chemical equipment

**Comment by auburncivilnetworks** [comment]
Chemist needs to be removed as it was meant to be replaced by pharmacist, but when the job was created it duplicated

**Comment by Raptor731** [comment]
then have them remove it them, but either or works
