### ISSUE TITLE
Scrap Dealer is unusable after restart

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#591]
**Title of the Bug**
Scrap Dealer is unusable after restart

**Description**
After the restart the Scrap Dealer VNPC is unusable. When you try to interact with it you get the message you are too far away and or not looking at him. This requires a Sr. Admin to remove and replace it to fix it 

**Steps to Reproduce**
1. Become D-class soon after server restart 
2. Speak to the scrap dealer 

**Expected Behavior**
It opens the scrap menu where you can buy stuff 

**Actual Behavior**
You get a message saying that you are too far away and/or not looking at it (despite the fact you are) 

**Evidence**
N/A

**Comment by ellie00001** [comment]
https://medal.tv/games/garrys-mod/clips/29wOMenB_AJHsa/d1337RinL1qB?invite=cr-MSxqdFQsODI5NzQ1NTUs

**Comment by ellie00001** [comment]
Fixed - problem was caused by having 2 instances of the scrap dealer
