### ISSUE TITLE
Combat medic requires whitelist message is incorrect

### ISSUE THREAD

**Issue by Shepardx64** [civilnetworks-projects/SCP_Public_Development#598]
### Description
When you swap on to CM without the whitelist it says you need to be whitelisted by an ambassador or dpt director instead of by a consultant or dpt director
### Steps to reproduce
Unwhitelist yourself
flag on Combat medic
Read bottom right text

### Expected behaviour
It informs you a consultant or department director will need to whitelist you

### Actual Behaviour
It tells you an ambassador or dpt director must whitelist you instead

### Evidence

![Image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/168373109/0cdb0649-8a35-43f1-b72b-fe2458a6d42a)

**Comment by CNCanoon** [comment]
To be checked by Content.

**Comment by CNCanoon** [comment]
Still an ongoing issue.
