### ISSUE TITLE
Tesla gates not working

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#604]
**Tesla gate do not work** 

**Description**
When you go through/near a tesla gate it does not trigger.

**Steps to Reproduce**
1. Go up to a functioning tesla gate (while the box is on and the switches a flipped on)
2. Go through 

**Expected Behavior**
It will trigger the electricity 

**Actual Behavior**
Nothing happens 

**Evidence**
https://medal.tv/games/garrys-mod/clips/2cNFKARejAK5sU/d1337f18yyVI?invite=cr-MSxEWXosMTk4Mzk5MTg2LA

**Comment by McYeke** [comment]
Tesla is working - as of 10/09/24
