### ISSUE TITLE
CI's kill house targets broken

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#615]
**Description**
CI's targets doesn't have a hitbox to register shots for it to proceed with the rest of the course

**Steps to Reproduce**
1. Run the kill house
2. Try to shoot the first target
3.

**Expected Behaviour**
The targets are supposed to go down and the door to the left open to the next room

**Actual Behaviour**
No hits being registered on the target

**Evidence**
https://medal.tv/games/garrys-mod/clips/2dlKAmqyGTrrSf/d1337WaAatUE?invite=cr-MSxycU4sNzExMzQ5Mjcs

**Comment by CNCanoon** [comment]
To be checked by Content.

**Comment by Naffenz** [comment]
Still a bug

**Comment by HerrKvarkar** [comment]
Duplicate of #544 on Private
