### ISSUE TITLE
!Time menu discrepancies

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#617]
**Description**
The !time menu shows a different time for the different sections i.e 1hr/24hrs/7d. These differences in time are thought to be causes by the timing pausing when viewing various parts of the menu. Additionally the discrepancy in time seems to scale with the difference in seconds increasing the larger the scale so 12hrs would have a smaller difference in time compared to 1 month each adding onto the time recorded. This means the longer the period that section of the !time menu covers the more time it will have recorded you having on the server in that instance

**Steps to Reproduce**
1. type !time
2. Check your current sessions' recorded time on each section
3. note down the difference in time

**Expected Behaviour**
Each section should show an equal amount of time recorded

**Actual Behaviour**
The amount of time recorded increases the longer the period that section of the menu covers to 1hr would have the smallest number and 1 month would have the longest

**Evidence**
N/A

**Comment by CNCanoon** [comment]
I believe its fixed by the new system but to be checked.

**Comment by CNCanoon** [comment]
Appears to be working now. If this becomes an ongoing issue, please recreate.
