### ISSUE TITLE
Add a PA system

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#618]
Add an entity that when interacted with will broadcast your voice to the sight for a period of time. (Bonus points if possible make it so it can broadcast exclusively to a certain area (e.g Floor 3))

**Comment by RequisJaquavian** [comment]
Some ideas alongside this;

- Would be nice if this would play a "ding/beep" or any sort of sound to indicate broadcast is beginning/ending 

- Also making it only broadcast it through facility speakers (ie. a bigger voice amp I suppose) 

- Some sort of ability to modify clearance, team, or other helpful configuration when setting it up if possible

**Comment by auburncivilnetworks** [comment]
Closing as unneeded, and we have a lack of trust for members of the community not to misuse this
