### ISSUE TITLE
!tempgag ULX command, potentially restrict !gag

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#62]
Allows for junior staff to have access to !tempgag and senior staff to have the more permanent !gag command. Makes it easier than having to time when to ungag when !tempmute is already a thing.

**Comment by AlphaToon** [comment]
Created the module for this, currently awaiting upload for testing before live push.

**Comment by AlphaToon** [comment]
Was added to all CN servers
