### ISSUE TITLE
Make electrical centre outer door have a tech expert override

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#620]
Make it so a CL2 techie can open the CL4 doors to electrical centres.

**Comment by auburncivilnetworks** [comment]
Unfortunately, this is being overruled. One of the guidelines provided is to consider clearances of areas when assigning special access. 
The electrical centres are CL4, letting a CL2 in there is a large security risk. Thus they will need to be escorted when entering.

FYI this was one of the examples of what not to do when the Special Access system was added. This will not be happening.

An Extract from the Guide Book on how to implement Special Clearance, written by the executive team, can be read below
> Special clearance should only be used to give jobs access to areas that make sense incharacter.
> Jobs that would not be trusted in character to enter an area unsupervised should not be given special clearance (e.g., a Tech Expert should not be given access to Floor 3 electrical simply because it would make it easier for them to fix broken electrical boxes)
