### ISSUE TITLE
Barricade Placer

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#628]
# Barricade Placer
**Feature description**
A SWEP Similar to the Instance Tool Placer and the Quarantine Placer, which allows IA to place Police Barricades down in the site to block player movement. It could be used for Riot Control, Checkpoints, Crime Scene Investigation, etc.

**Specification**
Identical Functioning to the Quarantine Placer and Instance Tool Placer
Prop list contains:
- models/props_fortifications/police_barrier001_128_reference.mdl (Limit: 1)
  - Prop Retextured as provided by Art Dev Frostbyte

![Image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/156694839/71035127-b972-40a7-a4fe-49a77312a20b)

![Image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/156694839/aeb7ae09-aab4-4404-9616-3e7a6dbee226)

**Comment by RequisJaquavian** [comment]
Cone prop too! 

![image](https://github.com/civilnetworks-projects/SCP_Public_Development/assets/114439603/e24b6c0f-af26-4afa-81ab-c316cf9d7f9b)

Model path: models/props_junk/trafficcone001a.mdl (Limit 3)

**Comment by auburncivilnetworks** [comment]
This is done
