### ISSUE TITLE
Give the keys swep to humanoid SCPS

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#631]
**Enhancement description**
This will allow humanoid SCPs such as 22415 and 912 to walk around without the need to have something in there hands.

**Specification**
Give them the keys swep when they spawn in.

**Comment by McYeke** [comment]
- [x] SCP-22415-1
- [x] SCP-22415-2
- [x] SCP-22415-3
- [x] SCP-912
