### ISSUE TITLE
Reality Bending Nerf + SRA Range Buff

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#647]
Following are value changes, I'm unaware of it's complexity:

**SCP-8837:** (has its unique abilities and energy level with the same reality bending SWEP)

- [ ] **Compress**
Increase from 40 energy --> 50 energy
Increase cooldown from 15 seconds --> 30 seconds
- [ ] **Black hole** 
Increase from 60 energy --> 70 energy
Increase cooldown from 90 seconds --> 100 seconds
- [ ] **Warp** 
Decrease cooldown from 15 --> 10 seconds
- [ ] **Suspension**
Increase energy from 30 --> 35
Increase cooldown from 15 seconds --> 20 seconds

**TYPE-GREEN(A/B) + Chaos Insurgency TYPE-BLUE:** (read paragraph below)

- [ ] **Explode Head**
 Increase from 40 energy --> 50 energy
 Increase cooldown from 15 seconds --> 30 seconds 
- [ ] **Inversion**
Increase energy cost from 15 per 5 seconds to 25 per 5 seconds
- [ ] **Escape Card**
Decrease energy cost from 50 --> 40
- [ ] **Dissolve**
Increase cooldown from 15 seconds --> 35 seconds
- [ ] **Detain** 
Increase cooldown from 15 seconds --> 50 seconds
- [ ] **Destabilize** 
Decrease energy 50 --> 45

These changes would effect Foundation Thaumatologist, UNGOC Thaumatologist, and D-Class TYPE-BLUE due to the same reality bending SWEP. However, if it is possible I'd hope that they aren't modified- something similar to how 8837 has different abilities and values, while using the same SWEP. 

**SCRANTON REALITY ANCHOR:**

- [ ] Increase TYPE-GREEN & 8837 suppression range from 400 --> 700
- [ ] Increase TYPE-BLUE suppression range from 800 --> 850

**Instakill abilities:**
- [ ] Decreased minimum HP to be invulnerable to reality bending instakill from 250 HP -> 225 HP

**Targeting:**
- [ ] Decrease max range of targeting from 2500 units to 2200 units.

**Comment by McYeke** [comment]
Completed rest for testing, except

SCRANTON REALITY ANCHOR:

 Increase TYPE-GREEN & 8837 suppression range from 400 --> 700
 Increase TYPE-BLUE suppression range from 800 --> 850

Due to the way the system works (maths!)

**Comment by McYeke** [comment]
closed - uploaded to live will be monitored
