### ISSUE TITLE
FAdmin Weapon Giver Enhancements

### ISSUE THREAD

**Issue by liondadev** [civilnetworks-projects/SCP_Public_Development#648]
## FAdmin Weapon Giver Enhancements

This ticket is related to the FAdmin weapon giver UI, the one accessed by clicking someone in the tab menu and going to "Give Weapon"

### Spec
The weapon giver UI should be updated as follows:
- Convert to VDerma
- Add a search bar at the top
- If a weapon doesn't have an icon, a SpawnIcon should be used with the weapon's world model

> [!NOTE]
> This can be done by either [modifying the DarkRP core files in the civilnetworks/darkrp repo](https://github.com/civilnetworks/DarkRP/blob/master/gamemode/modules/fadmin/fadmin/playeractions/giveweapons/cl_controls.lua), or creating another addon that [overrides the derma control that FAdmin makes](https://github.com/civilnetworks/DarkRP/blob/master/gamemode/modules/fadmin/fadmin/playeractions/giveweapons/cl_controls.lua#L164) for this. Either is fine, creating another addon is preferred because it means we don't need to do anything weird if the file is updated upstream and we need to merge it in.

**Comment by ghost** [comment]
This has been completed and uploaded to our live servers
