### ISSUE TITLE
CI Respawn Cooldown For SCPs

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#652]
### Description
When a Player on a CI Character flags onto an SCP, any Foundation Player they kill will have a respawn cooldown higher than normal. This is because it registers them as being killed by a player of another faction.

This is incredibly unbalanced as the players fighting the breach will be saddled by 4x longer respawn times than normal.

In order to fix this, the easiest solution is to only allow players to flag onto SCPs when playing a Foundation Character. Another option would be for a core dev to write an exception for SCPs such that they do not apply increased cooldown times to opposite faction players.

**Comment by auburncivilnetworks** [comment]
@McYeke

**Comment by HerrKvarkar** [comment]
Double check this
