### ISSUE TITLE
Let Foundation CL5 and Site Director call ERT

### ISSUE THREAD

**Issue by EdwinCNdev** [civilnetworks-projects/SCP_Public_Development#664]
**Forum link** 
https://civilnetworks.net/community/threads/let-o5-ethics-site-director-call-e-r-t.26123/page-3#post-189064

**Enhancement description**
Add a way for CL5 and the Site director to force trigger an ERT spawn. 

**Specification**
- An entity for the relevant jobs to interact with (https://discord.com/channels/847587034792460328/917136343665082429/1266619648875565147)
- Allow the caller to choose a number of teams to call (1-3)
- Restricted to Site Director and CL5 (O5 and Ethics) or a vjobeditor flag or keycard based 
- Any extra flavour text when interacting with the entity

**Comment by ghost** [comment]
Ticket is now completed by Ventz after introduction of the ERT phone.
