### ISSUE TITLE
Voice mute gagged player

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#666]
**Mute a player's voice chat when gagged with a restraint, disabling the ability to speak entirely unless they get ungagged.**

Restraints:
- weapon_leash_rope
- weapon_cuff_rope
- weapon_leash_elastic
- weapon_cuff_elastic
- weapon_cuff_scp

*Extra, if possible:* Disable the ability to use chat, excluding **/looc** and **/ooc**

**Comment by ghost** [comment]
I believe there is a performance reason for why we don't do this already. I will ask Ventz.

**Comment by ghost** [comment]
Closing on the request of Ventz as this is not desirable at this time due to performance considerations.
