### ISSUE TITLE
Ktime graph inaccuracy

### ISSUE THREAD

**Issue by Solid-Snake420** [civilnetworks-projects/SCP_Public_Development#698]
Description
(What is the problem?)

Steps to Reproduce
(Your goto way to recreate this bug.)
1. Open ktime menu and go on the monthly page
2. Compare other menus in the same time period
3. Note that there will be a discrepancy between time measured on the graph on the different time frames

Expected Behaviour
The time played displayed visually should be universally consistent

Actual Behaviour
There will be time bars missing and other discrepancies where time has been played and not displayed on graph

Evidence

![Image](https://github.com/user-attachments/assets/77f5ea44-4705-4781-b8a2-d96b61e6a534)

https://medal.tv/games/garrys-mod/clips/isK1ha8WjTxDbd5nJ/d1337WfOUv9T?invite=cr-MSxrY0UsMTY4MDE2NDU4LA

**Comment by HerrKvarkar** [comment]
Could you please provide more examples of what you mean. I am finding it quite difficult to understand just from this one image

**Comment by Solid-Snake420** [comment]
Sure its not super easy to provide proof however, its mostly that its not
logging the same amount of time as steam is within a similar period. Or if
it is its not giving it a green bar on the display like it should
