### ISSUE TITLE
Non-Specialised Overhaul

### ISSUE THREAD

**Issue by auburncivilnetworks** [civilnetworks-projects/SCP_Public_Development#709]
### Description
A simpler project for Harry to start with on SCP to get used to mapping in the style of the Foundation aesthetic.

We discussed a few ideas involving making each chamber more suited to its SCP e.g.
- 912 CC themed around an armoury
- 999 CC themed around a playground with a sandbox
- 2295 themed around a textiles/sewing shop
- etc

It would also be appreciated if more non-specialised chambers were added for events and miscellaneous roleplay

**Comment by CNHarryMRP** [comment]
Check Private GH for more explanation
