### ISSUE TITLE
LCZ Non Specialised containment rework

### ISSUE THREAD

**Issue by McYeke** [civilnetworks-projects/SCP_Public_Development#719]
**Enhancement description**
Reworking of the LCZ Non Specialised Containment area to create a more specialised zone for the 4 SCPs, blending our own spin on the chambers with established lore (see wikidot articles)

- [x] SCP-999 [Wikidot](https://scp-wiki.wikidot.com/scp-999)
- [x] SCP-912 [Wikidot](https://scp-wiki.wikidot.com/scp-912)
- [x] SCP-2295 [Wikidot](https://scp-wiki.wikidot.com/scp-2295)
- [ ] SCP-073 [Wikidot](https://scp-wiki.wikidot.com/scp-073)

Include reworked design for "non specialised containment" zones for future additions

Bounty approved for £100 by Ventz

**Comment by McYeke** [comment]
Bounty under review to paramater change

**Comment by CNHarryMRP** [comment]
Judge & Harry Duel ticket

**Comment by McYeke** [comment]
Bounty reviewed and updated to £200 - Split evenly

**Comment by CNHarryMRP** [comment]
912 finished

**Comment by CNHarryMRP** [comment]
PROPCOMBINE 2295 [REMINDER TO SELF]

**Comment by CNHarryMRP** [comment]
2295 mostly done

**Comment by CNHarryMRP** [comment]
My side of the ticket is fully done and has been sent off

**Comment by the-judged** [comment]
Complete, awaiting map integration.✅

**Comment by CNHarryMRP** [comment]
My bounty has been paid

**Comment by CNHarryMRP** [comment]
Has been merged into the map
