### ISSUE TITLE
[Scrap Dealer] announcement appear only on D-Class

### ISSUE THREAD

**Issue by RequisJaquavian** [civilnetworks-projects/SCP_Public_Development#735]
Make the ``[Scrap Dealer] The scrap dealer now has guns available for purchase!`` and all other ``[Scrap Dealer]`` announcements only be visible to players on D-Class jobs:

TEAM_CLASS_D_BRUTE
TEAM_CLASS_D_JANITOR
TEAM_CLASS_D_PERSONNEL
TEAM_CLASS_D_SCOUT
TEAM_CLASS_D_TYPEBLUE
TEAM_CLASS_D_TYPEBLUE_REFUND

**Comment by ghost** [comment]
Closing due to entire scrap system remake being in progress.
