### ISSUE TITLE
Add an announcement when sitewide lockdown is enabled

### ISSUE THREAD

**Issue by Solid-Snake420** [civilnetworks-projects/SCP_Public_Development#759]
https://civilnetworks.net/community/threads/site-wide-lockdown-qol.28745/

**Enhancement description**
It would involve adding an announcement via the facility announcement system voice telling people that "Site wide lockdown is enabled. Seek shelter".

**Specification**
This would be activated when sitewide lockdown is toggled and would also come up in text and the facility announcement voice.

**Comment by JacubRSTNC** [comment]
Duplicate of https://github.com/civilnetworks-projects/SCP_Private_Development/issues/323
