### ISSUE TITLE
swap the water to bottled water in the scavenging pool

### ISSUE THREAD

**Issue by Raptor731** [civilnetworks-projects/SCP_Public_Development#770]
**Forum link** 
(https://civilnetworks.net/community/threads/add-bottled-water-vcraft_item_bottled_water-as-a-scavengable-item.29524/)

**Enhancement description**
Swap the vcraft water with the vcraft bottle water in the scavenging so people are able to make perfect recipes that include water

**Specification**
This would swap vcraft_item_water with vcraft_item_bottle_water

**Comment by Raptor731** [comment]
supers can do this

**Comment by World3cr** [comment]
Completed

**Comment by World3cr** [comment]
Completed
