### ISSUE TITLE
Memetic Kill Agent for Documents/SCIPnet Folders

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks-projects/SCP_Public_Development#9]
https://www.civilgamers.com/community/threads/memetic-kill-agent-security-intergration.3924/#post-25344

**Comment by Kw1ll** [comment]
Merged with [#282](https://github.com/civilnetworks/SCP_Private_Development/issues/282)

**Comment by ghost** [comment]
Has this been completed?

**Comment by LordMirai** [comment]
Actual work underway:
- Fix non-functional memetic kill agent
- QoL changes of https://civilgamers.com/community/threads/clipboard-document-qol-improvements.13081/

**Comment by ghost** [comment]
Moved to revision required. No specification given.

**Comment by auburncivilnetworks** [comment]
Reaffirmed as wanted by Content Team

**Comment by McYeke** [comment]
Closing this ticket- new one to be made with actual feature specification.
